[tools]
rojo = { source = "rojo-rbx/rojo", version = "7.3.0" }
selene = { source = "Kampfkarren/selene", version = "0.25.0" }
stylua = { source = "JohnnyMorganz/stylua", version = "0.18.1" }
luau-lsp = { source = "JohnnyMorganz/luau-lsp", version = "*" }
