--!strict

--- Asset IDs for images used in the plugin's toolbar and UI.
--- These are Roblox asset IDs pointing to uploaded images.

local Assets = {}

--- Default icon
Assets.Icon = "rbxassetid://11115506617"

--- Icon with a green square indicating connection
Assets.ConnectedIcon = "rbxassetid://11116536087"

--- Icon for the settings button in the toolbar.
Assets.SettingsIcon = "rbxassetid://13997395868"

return Assets
