--!strict

--- Asset IDs for images used in the plugin's toolbar and UI.
--- These are Roblox asset IDs pointing to uploaded images.

local Assets = {}

--- Default icon
Assets.Icon = "rbxassetid://85321628471210"

--- Icon with a green square indicating connection
Assets.ConnectedIcon = "rbxassetid://126078034992458"

--- Icon for the settings button in the toolbar.
Assets.SettingsIcon = "rbxassetid://111753866426868"

return Assets
