name: cpp-linter

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Compile Commands
        run: |
        mkdir build && cd build
        cmake ..
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE --build . --target Luau.LanguageServer.CLI -j 3

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          ignore: .github|extern|luau
          files-changed-only: false
          tidy-checks: ""

      - name: Verify
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
