name: Upload Companion Plugin (Manual)

on:
  workflow_dispatch:

jobs:
  upload-plugin:
    name: Upload Roblox Studio Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ok-nick/setup-aftman@v0.4.2

      - name: Build Plugin
        run: rojo build plugin --output Luau.rbxm

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Luau.rbxm
          path: Luau.rbxm

      - name: Publish Plugin to Roblox
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        working-directory: plugin
        run: |
          rojo build test.project.json --output plugin_place.rbxl
          lune run cloud/execute_task.luau plugin_place.rbxl cloud/publishing_task.luau
